/* Ausgabe fuer After Effects: das ExtendScript-Skript als .jsx. */

// Das Layout ist fuer 1920x1080 entworfen. Auf einer anderen Leinwand behaelt
// jedes Element seinen Abstand zur unteren linken Ecke und seine Groesse im
// selben Verhaeltnis - der Faktor ist fuer beide Achsen gleich, damit nichts
// verzerrt. Bei 1920x1080 ist er 1 und alles bleibt, wie es war.
var AE_W=1920, AE_H=1080;
function aeFaktor(c){ return Math.min(c.W/AE_W, c.H/AE_H); }
function aePunkt(c,x,y){ var k=aeFaktor(c); return [x*k, c.H-(AE_H-y)*k]; }
function aeOrt(c,x,y){ return aeXY(aePunkt(c,x,y)); }
function aeMass(c,n){ return aeNum(n*aeFaktor(c)); }

function aeSafeComment(s){
  return String(s == null ? '' : s)
    .replace(/[\u0000-\u001f\u007f-\u009f\u2028\u2029]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120);
}
function aeNum(n){ var v=(typeof n==='number'&&isFinite(n))?n:0; return (Math.round(v*1e4)/1e4).toString(); }
function aeStr(s){ return '"'+String(s).replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r?\n/g,'\\n')+'"'; }
function aeCol(hex){ var c=hexToRgb(hex); return '['+aeNum(c[0]/255)+','+aeNum(c[1]/255)+','+aeNum(c[2]/255)+']'; }
function aeXY(p){ return '['+aeNum(p[0])+','+aeNum(p[1])+']'; }
function aeList(arr){ return '['+arr.join(',')+']'; }
function aePts(pts){ var o=[]; for(var i=0;i<pts.length;i++) o.push(aeXY(pts[i])); return aeList(o); }
function aeKf(kfs,dec){
  var d=(dec==null)?3:dec, o=[], m=Math.pow(10,d);
  for(var i=0;i<kfs.length;i++){
    var v=kfs[i][1];
    o.push('['+kfs[i][0]+','+(Array.isArray(v)?aeXY(v):(Math.round(v*m)/m))+']');
  }
  return aeList(o);
}
function aeDuration(){
  var c=cfg();
  var fps=parseFloat(c.fps)||30;
  if(!speedData.length) return 10;
  var drift=parseFloat(c.driftFactor)||1.0;
  var offset=parseFloat(c.offset)||0;
  var span=(speedData[speedData.length-1].time-speedData[0].time)/1000*drift+offset;
  return Math.max(1, Math.ceil((span+1)*fps)/fps);
}

function aeHead(compName){
  var c=cfg();
  var fps=parseFloat(c.fps)||30;
  return [
'// ─────────────────────────────────────────────────────────────────────────────',
'// '+compName+' — generated by Activity Layers',
'// Source: '+(aeSafeComment(currentFilename)||'GPS track'),
'// After Effects:  File > Scripts > Run Script File…',
'// Creates a new '+c.W+'x'+c.H+' comp. Values are driven by Slider Control',
'// keyframes, so you can restyle the layers without losing the animation.',
'// Values are smoothed and, where the device recorded none, reconstructed from',
'// GPS positions. Use them for display, not as measurements.',
'// ─────────────────────────────────────────────────────────────────────────────',
'(function(){',
'  if (typeof app === "undefined" || !app.project) { alert("Please run this from inside After Effects."); return; }',
'  var STEP = "starting up";',
'  function step(name, fn){ STEP = name; return fn(); }',
'  try {',
'  app.beginUndoGroup("Activity Layers – '+compName+'");',
'  var W='+c.W+', H='+c.H+', FPS='+aeNum(fps)+', DUR='+aeNum(aeDuration())+';',
'  var comp = app.project.items.addComp('+aeStr(compName)+', W, H, 1, DUR, FPS);',
'  var F = 1/FPS;',
'',
'  function tf(L,mn){ return L.property("ADBE Transform Group").property(mn); }',
'  function shapeLayer(name){',
'    STEP = "creating shape layer \\"" + name + "\\"";',
'    var L=comp.layers.addShape(); L.name=name;',
'    tf(L,"ADBE Anchor Point").setValue([0,0]); tf(L,"ADBE Position").setValue([0,0]);',
'    return L;',
'  }',
'  function grpOf(L,name){',
'    var g=L.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group");',
'    if(name) g.name=name;',
'    return g.property("ADBE Vectors Group");',
'  }',
'  function addPath(c,verts,closed){',
'    STEP = "drawing a path (" + verts.length + " points)";',
'    var p=c.addProperty("ADBE Vector Shape - Group");',
'    var s=new Shape(); s.vertices=verts; s.closed=!!closed;',
'    var z=[]; for(var i=0;i<verts.length;i++) z.push([0,0]);',
'    s.inTangents=z; s.outTangents=z;',
'    p.property("ADBE Vector Shape").setValue(s);',
'    return p;',
'  }',
'  function addEllipse(c,size,pos){',
'    STEP = "drawing an ellipse";',
'    var e=c.addProperty("ADBE Vector Shape - Ellipse");',
'    e.property("ADBE Vector Ellipse Size").setValue(size);',
'    if(pos) e.property("ADBE Vector Ellipse Position").setValue(pos);',
'    return e;',
'  }',
'  function addRect(c,size,pos,round){',
'    var r=c.addProperty("ADBE Vector Shape - Rect");',
'    r.property("ADBE Vector Rect Size").setValue(size);',
'    if(pos) r.property("ADBE Vector Rect Position").setValue(pos);',
'    if(round) r.property("ADBE Vector Rect Roundness").setValue(round);',
'    return r;',
'  }',
'  function addFill(c,color){',
'    STEP = "applying a fill colour";',
'    var f=c.addProperty("ADBE Vector Graphic - Fill");',
'    f.property("ADBE Vector Fill Color").setValue(color);',
'    return f;',
'  }',
'  function addStroke(c,color,width){',
'    STEP = "applying a stroke";',
'    var s=c.addProperty("ADBE Vector Graphic - Stroke");',
'    s.property("ADBE Vector Stroke Color").setValue(color);',
'    s.property("ADBE Vector Stroke Width").setValue(width);',
'    s.property("ADBE Vector Stroke Line Cap").setValue(2);',
'    s.property("ADBE Vector Stroke Line Join").setValue(2);',
'    return s;',
'  }',
'  function addTrim(c,start,end,offset){',
'    STEP = "adding Trim Paths";',
'    var t=c.addProperty("ADBE Vector Filter - Trim");',
'    if(start!=null) t.property("ADBE Vector Trim Start").setValue(start);',
'    if(end!=null) t.property("ADBE Vector Trim End").setValue(end);',
'    if(offset!=null) t.property("ADBE Vector Trim Offset").setValue(offset);',
'    return t;',
'  }',
'  function keys(prop,kfs){ STEP = "writing " + kfs.length + " keyframes"; for(var i=0;i<kfs.length;i++) prop.setValueAtTime(kfs[i][0]*F, kfs[i][1]); return prop; }',
'  function slider(L,name,kfs){',
'    STEP = "adding the slider control \\"" + name + "\\"";',
'    var e=L.property("ADBE Effect Parade").addProperty("ADBE Slider Control"); e.name=name;',
'    return keys(e.property("ADBE Slider Control-0001"), kfs);',
'  }',
'  function textLayer(name,str,pos,size,color,center){',
'    STEP = "creating text layer \\"" + name + "\\"";',
'    var L=comp.layers.addText(str); L.name=name;',
'    var td=L.property("ADBE Text Properties").property("ADBE Text Document");',
'    var d=td.value;',
'    d.fontSize=size; d.fillColor=color; d.applyFill=true; d.applyStroke=false;',
'    d.justification = center ? ParagraphJustification.CENTER_JUSTIFY : ParagraphJustification.LEFT_JUSTIFY;',
'    td.setValue(d);',
'    tf(L,"ADBE Anchor Point").setValue([0,0]);',
'    tf(L,"ADBE Position").setValue(pos);',
'    return L;',
'  }',
'  function driveText(L,fx,kfs,expr){',
'    STEP = "linking the text to the slider \\"" + fx + "\\"";',
'    slider(L,fx,kfs);',
'    L.property("ADBE Text Properties").property("ADBE Text Document").expression =',
'      \'var v = effect("\'+fx+\'")(1).value; \'+expr;',
'  }',
''].join('\n');
}
function aeTail(){
  return ['',
'  comp.openInViewer();',
'  app.endUndoGroup();',
'  } catch (err) {',
'    try { app.endUndoGroup(); } catch (e) {}',
'    alert("Activity Layers could not finish this overlay.\\n\\n"',
'      + "Step: " + STEP + "\\n"',
'      + "After Effects said: " + (err && err.message ? err.message : String(err)) + "\\n"',
'      + (err && err.line ? "Line: " + err.line + "\\n" : "")',
'      + "\\nPlease report this message at\\n"',
'      + "https://github.com/hellowebcode/activitylayers/issues");',
'  }',
'})();',''].join('\n');
}

// Liefert die Hauptspur und, falls vorhanden, die Geisterspur. Beide teilen
// sich einen Rahmen, sonst laegen sie nicht uebereinander.
function aeRoutePoints(c,pad){
  pad=pad*aeFaktor(c);
  var merc=function(lat){ return Math.log(Math.tan(Math.PI/4+lat*Math.PI/360)); };
  var rahmen=rawPoints.concat(ghostPoints);
  var xs=[],ys=[];
  for(var i=0;i<rahmen.length;i++){ xs.push(rahmen[i].lon*Math.PI/180); ys.push(merc(rahmen[i].lat)); }
  var mnx=minOf(xs), mxx=maxOf(xs);
  var mny=minOf(ys), mxy=maxOf(ys);
  var sw=c.W-2*pad, sh=c.H-2*pad;
  var s=Math.min(sw/((mxx-mnx)||1), sh/((mxy-mny)||1));
  var ox=pad+(sw-(mxx-mnx)*s)/2, oy=pad+(sh-(mxy-mny)*s)/2;
  function aufLeinwand(liste){
    var out=[];
    for(var j=0;j<liste.length;j++)
      out.push([ox+(liste[j].lon*Math.PI/180-mnx)*s, oy+(mxy-merc(liste[j].lat))*s]);
    return out;
  }
  return { track: aufLeinwand(rawPoints), ghost: aufLeinwand(ghostPoints) };
}

function aePathKeys(dataArr, pts){
  var idx=buildKeyframeList(dataArr,function(p,i){return i;});
  var out=[];
  for(var i=0;i<idx.length;i++){ var p=pts[idx[i][1]]; if(p) out.push([idx[i][0],p]); }
  return out;
}

function buildSpeedJsx(){
  var c=cfg();
  if(!speedData.length) return null;
  var maxSpd=parseFloat(c.maxSpeed)||9;
  var unit=unitDisplay(c.unit);
  var kf=buildKeyframeList(speedData,function(p){return Math.min(p.spd,maxSpd);});
  var CX=320, CY=760, DISC=200, R=148, SPAN=86.111, OFF=205;
  var vs=ankerVersatz(c,'speed',OVERLAY_MASSE.speed,CX,CY); CX+=vs.dx; CY+=vs.dy;
  var L=[aeHead('Speed Overlay')];
  L.push('  // Gap of 50° at the bottom: the ring covers '+SPAN+'% of the circle, rotated by '+OFF+'°.');
  L.push('  var MAXS='+aeNum(maxSpd)+', SPAN='+SPAN+';');
  L.push('  var disc=shapeLayer("Gauge Backdrop"), dg=grpOf(disc,"Disc");');
  L.push('  addEllipse(dg,['+aeMass(c,DISC*2)+','+aeMass(c,DISC*2)+'],'+aeOrt(c,CX,CY)+');');
  L.push('  addFill(dg,'+aeCol(c.gaugeBgColor)+');');
  L.push('  var ring=shapeLayer("Gauge Ring"), rg=grpOf(ring,"Ring");');
  L.push('  addEllipse(rg,['+aeMass(c,R*2)+','+aeMass(c,R*2)+'],'+aeOrt(c,CX,CY)+');');
  L.push('  addStroke(rg,'+aeCol(c.gaugeRingColor)+','+aeMass(c,20)+');');
  L.push('  addTrim(rg,0,SPAN,'+OFF+');');
  L.push('  var arc=shapeLayer("Speed Arc"), ag=grpOf(arc,"Arc");');
  L.push('  addEllipse(ag,['+aeMass(c,R*2)+','+aeMass(c,R*2)+'],'+aeOrt(c,CX,CY)+');');
  L.push('  addStroke(ag,'+aeCol(c.gaugeArcColor)+','+aeMass(c,24)+');');
  L.push('  var at=addTrim(ag,0,0,'+OFF+');');
  L.push('  keys(at.property("ADBE Vector Trim End"), (function(k){');
  L.push('    var o=[]; for(var i=0;i<k.length;i++) o.push([k[i][0], k[i][1]/MAXS*SPAN]); return o;');
  L.push('  })('+aeKf(kf)+'));');
  L.push('  var num=textLayer("Speed Value","0.0",'+aeOrt(c,CX,CY+18)+','+aeMass(c,76)+','+aeCol(c.gaugeNumberColor)+',true);');
  L.push('  driveText(num,"Speed",'+aeKf(kf)+',"v.toFixed(1);");');
  L.push('  textLayer("Speed Unit",'+aeStr(unit)+','+aeOrt(c,CX,CY+78)+','+aeMass(c,30)+','+aeCol(c.gaugeUnitColor)+',true);');
  L.push(aeTail());
  return L.join('\n');
}

function buildRouteJsx(){
  var c=cfg();
  if(rawPoints.length<2) return null;
  var spuren=aeRoutePoints(c,90);
  var pts=spuren.track;
  var tw=parseFloat(c.trackW)||6;
  var dr=parseFloat(c.dotR)||12;
  var so=zahlOderVorgabe(c.shadowOffset,5);
  var dotKf=aePathKeys(rawPoints,pts);
  var L=[aeHead('Route Overlay')];
  if(spuren.ghost.length>1){
    var gAlpha=Math.max(0.05,Math.min(1,zahlOderVorgabe(c.ghostAlpha,0.55)));
    L.push('  var gh=shapeLayer("Ghost Track"), gg=grpOf(gh,"Path");');
    L.push('  addPath(gg,'+aePts(spuren.ghost)+',false);');
    L.push('  addStroke(gg,'+aeCol(c.ghostColor||'#8892a4')+','+aeNum(parseFloat(c.ghostW)||4)+');');
    L.push('  tf(gh,"ADBE Opacity").setValue('+aeNum(gAlpha*100)+');');
  }
  L.push('  var PTS='+aePts(pts)+';');
  L.push('  var sh=shapeLayer("Route Shadow"), sg=grpOf(sh,"Path");');
  L.push('  addPath(sg,PTS,false);');
  L.push('  addStroke(sg,'+aeCol(c.shadowColor)+','+aeNum(tw*SHADOW_WIDTH_RATIO)+');');
  L.push('  tf(sh,"ADBE Position").setValue(['+aeNum(so)+','+aeNum(so)+']);');
  L.push('  var tr=shapeLayer("Route Track"), tg=grpOf(tr,"Path");');
  L.push('  addPath(tg,PTS,false);');
  L.push('  addStroke(tg,'+aeCol(c.trackColor)+','+aeNum(tw)+');');
  L.push('  var dot=shapeLayer("Route Dot"), dg=grpOf(dot,"Dot");');
  L.push('  addEllipse(dg,['+aeNum(dr*2)+','+aeNum(dr*2)+'],[0,0]);');
  L.push('  addFill(dg,'+aeCol(c.dotColor)+');');
  L.push('  keys(tf(dot,"ADBE Position"),'+aeKf(dotKf,2)+');');
  L.push(aeTail());
  return L.join('\n');
}

function buildElevJsx(){
  var c=cfg();
  var elevPts=rawPoints.filter(function(p){return p.ele!==null && !isNaN(p.ele);});
  if(elevPts.length<2) return null;
  var iW=Math.min(c.W, parseFloat(c.elevW)||c.W);
  var iH=Math.min(c.H, parseFloat(c.elevH)||300);
  var lw=parseFloat(c.elevLineW)||2;
  var so=zahlOderVorgabe(c.elevShadowOffset,4);
  var fillOn=c.elevFill==='1';
  // Das Profil rechnet in Leinwandkoordinaten; der Anker verschiebt es im
  // Entwurfsmass und wird dafuer mitskaliert.
  // Das Profil wird waagerecht mittig gezeichnet. Der Anker nennt dagegen die
  // Lage am linken Rand, deshalb zaehlt hier die Strecke vom gezeichneten Ort
  // zum Ziel, nicht der Ankerversatz selbst.
  var massElev={b:iW/aeFaktor(c), h:iH/aeFaktor(c)};
  var linksX=ANKER_RAND+massElev.b/2, untenY=ENTWURF_H-120-massElev.h/2;
  var vs=ankerVersatz(c,'elev',massElev,linksX,untenY);
  var vdx=(linksX+vs.dx)-ENTWURF_W/2, vdy=(untenY+vs.dy)-untenY;
  var ox=(c.W-iW)/2+vdx*aeFaktor(c), oy=c.H-iH-120*aeFaktor(c)+vdy*aeFaktor(c);
  var xy=buildElevXY(elevPts,iW,iH,0);
  var pts=[],i;
  for(i=0;i<xy.xs.length;i++) pts.push([ox+xy.xs[i], oy+xy.ys[i]]);
  var closed=pts.slice();
  closed.push([ox+xy.xs[xy.xs.length-1], oy+iH]);
  closed.push([ox+xy.xs[0], oy+iH]);
  var dotKf=aePathKeys(elevPts,pts);
  var L=[aeHead('Elevation Overlay')];
  L.push('  var PTS='+aePts(pts)+';');
  if(fillOn){
    L.push('  var fl=shapeLayer("Elevation Fill"), fg=grpOf(fl,"Area");');
    L.push('  addPath(fg,'+aePts(closed)+',true);');
    L.push('  addFill(fg,'+aeCol(c.elevFillColor)+');');
  }
  L.push('  var sh=shapeLayer("Elevation Shadow"), sg=grpOf(sh,"Path");');
  L.push('  addPath(sg,PTS,false);');
  L.push('  addStroke(sg,'+aeCol(c.elevShadowColor)+','+aeNum(lw*SHADOW_WIDTH_RATIO)+');');
  L.push('  tf(sh,"ADBE Position").setValue([0,'+aeNum(so)+']);');
  L.push('  var ln=shapeLayer("Elevation Line"), lg=grpOf(ln,"Path");');
  L.push('  addPath(lg,PTS,false);');
  L.push('  addStroke(lg,'+aeCol(c.elevColor)+','+aeNum(lw)+');');
  L.push('  var dot=shapeLayer("Elevation Dot"), dg=grpOf(dot,"Dot");');
  L.push('  addEllipse(dg,[18,18],[0,0]);');
  L.push('  addFill(dg,'+aeCol(c.elevDotColor)+');');
  L.push('  keys(tf(dot,"ADBE Position"),'+aeKf(dotKf,2)+');');
  // Die Hoehenzahlen am linken Rand. Das Haekchen wirkte bisher nur in der
  // Vorschau auf der Seite.
  if(c.elevLabels){
    var marken=hoehenMarken(xy.minEle, xy.maxEle, c.unit);
    var beschX=ox+Math.max(28, iH*0.18);
    var einzug=Math.max(8, iH*0.06);
    var hoehenY=[oy+einzug, oy+iH/2, oy+iH-einzug];
    var beschGroesse=iH*0.09;
    for(var m=0;m<marken.length;m++){
      L.push('  textLayer("Elevation label '+(m+1)+'",'+aeStr(marken[m])+',['
        +aeNum(beschX)+','+aeNum(hoehenY[m])+'],'+aeNum(beschGroesse)+','+aeCol(c.elevColor)+',true);');
    }
  }
  L.push(aeTail());
  return L.join('\n');
}

function buildHRJsx(){
  var c=cfg();
  if(!hrData.length) return null;
  var sizeEntwurf=(parseFloat(c.hrSize)||0.07)*AE_H;
  var size=sizeEntwurf*aeFaktor(c);
  var kf=buildKeyframeList(hrData,function(p){return p.hr;});
  var HX=250, HY=880;
  var vs=ankerVersatz(c,'hr',OVERLAY_MASSE.hr,HX,HY); HX+=vs.dx; HY+=vs.dy;
  var ort=aeOrt(c,HX+sizeEntwurf*1.2,HY+sizeEntwurf*0.4);
  // Das Herz entsteht im Entwurfsmass und wandert dann als Ganzes auf die
  // Leinwand, damit Form und Ort zusammenbleiben.
  var sE=sizeEntwurf/22, heart=[], t;
  for(t=0;t<Math.PI*2;t+=Math.PI/36){
    var x=16*Math.pow(Math.sin(t),3);
    var y=13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t);
    heart.push(aePunkt(c, HX+x*sE, HY-y*sE));
  }
  var L=[aeHead('HR Overlay')];
  L.push('  var hl=shapeLayer("Heart"), hg=grpOf(hl,"Heart");');
  L.push('  addPath(hg,'+aePts(heart)+',true);');
  L.push('  addFill(hg,'+aeCol(c.hrHeartColor)+');');
  var zonen = c.hrZones ? zonenDeckkraft(hrData,function(p){return p.hr;},
    parseFloat(c.hrZone2)||140, parseFloat(c.hrZone3)||165) : null;
  if(zonen){
    var farben=[c.hrColor,c.hrColor2,c.hrColor3];
    for(var z=0;z<3;z++){
      L.push('  var z'+z+'=textLayer("HR zone '+(z+1)+'","0",'+ort+','+aeNum(size)+','+aeCol(farben[z])+',false);');
      L.push('  driveText(z'+z+',"HR zone '+(z+1)+'",'+aeKf(kf,0)+',"Math.round(v)+\\"\\";");');
      L.push('  keys(tf(z'+z+',"ADBE Opacity"),'+aeKf(zonen[z],0)+');');
    }
  } else {
    L.push('  var num=textLayer("HR Value","0",'+ort+','+aeNum(size)+','+aeCol(c.hrColor)+',false);');
    L.push('  driveText(num,"Heart Rate",'+aeKf(kf,0)+',"Math.round(v)+\\"\\";");');
  }
  L.push(aeTail());
  return L.join('\n');
}

function buildInclineJsx(){
  var c=cfg();
  if(!gradeData.length) return null;
  var unit=c.inclineUnit;
  var kf=buildKeyframeList(gradeData,function(p){return p.pct;});
  var rot=[],i;
  for(i=0;i<kf.length;i++) rot.push([kf[i][0], -Math.atan(kf[i][1]/100)*180/Math.PI]);
  var BX=260, BY=880;
  var vs=ankerVersatz(c,'incline',OVERLAY_MASSE.incline,BX,BY); BX+=vs.dx; BY+=vs.dy;
  var L=[aeHead('Incline Overlay')];
  L.push('  // The wedge rotates to the real slope angle; the number stays upright.');
  L.push('  var w=shapeLayer("Incline Wedge"), wg=grpOf(w,"Wedge");');
  L.push('  addPath(wg,[['+aeMass(c,-90)+',0],['+aeMass(c,90)+',0],['+aeMass(c,90)+','+aeMass(c,16)+'],['+aeMass(c,-90)+','+aeMass(c,16)+']],true);');
  L.push('  addFill(wg,'+aeCol(c.inclineWedgeColor)+');');
  L.push('  tf(w,"ADBE Anchor Point").setValue([0,0]);');
  L.push('  tf(w,"ADBE Position").setValue('+aeOrt(c,BX,BY)+');');
  L.push('  keys(tf(w,"ADBE Rotate Z"),'+aeKf(rot,2)+');');
  L.push('  var num=textLayer("Incline Value","0",'+aeOrt(c,BX,BY-70)+','+aeMass(c,84)+','+aeCol(c.inclineNumberColor)+',true);');
  if(unit==='deg') L.push('  driveText(num,"Incline",'+aeKf(kf,2)+',"(Math.atan(v/100)*180/Math.PI).toFixed(1)+\\"\\\\u00b0\\";");');
  else             L.push('  driveText(num,"Incline",'+aeKf(kf,2)+',"v.toFixed(1)+\\"%\\";");');
  L.push(aeTail());
  return L.join('\n');
}

function buildMileJsx(){
  var c=cfg();
  if(!distData.length) return null;
  var unit=c.unit;
  var dec=parseInt(c.mileDecimals,10)||1;
  var div=unit==='mph'?1609.344:1000;
  var label=unit==='mph'?'mi':'km';
  var kf=buildKeyframeList(distData,function(p){return p.distM/div;});
  var MX=260, MY=880;
  var vs=ankerVersatz(c,'mile',OVERLAY_MASSE.mile,MX,MY); MX+=vs.dx; MY+=vs.dy;
  var L=[aeHead('Mile Marker Overlay')];
  L.push('  var num=textLayer("Distance Value","0",'+aeOrt(c,MX,MY)+','+aeMass(c,88)+','+aeCol(c.mileColor)+',true);');
  L.push('  driveText(num,"Distance",'+aeKf(kf,3)+',"v.toFixed('+dec+');");');
  L.push('  textLayer("Distance Unit",'+aeStr(label)+','+aeOrt(c,MX,MY+54)+','+aeMass(c,34)+','+aeCol(c.mileLineDistColor)+',true);');
  L.push(aeTail());
  return L.join('\n');
}
